/** @type {import('tailwindcss').Config} */
const config = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx}",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class', // Enable manual toggling via 'dark' class
    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', 'sans-serif'],
                serif: ['Cormorant Garamond', 'serif'],
                headline: ['Newsreader', 'serif'],
                body: ['Manrope', 'sans-serif'],
                label: ['Manrope', 'sans-serif']
            },
            colors: {
                stone: {
                    50: '#fafaf9',
                    100: '#f5f5f4',
                    200: '#e7e5e4',
                    300: '#d6d3d1',
                    400: '#a8a29e',
                    500: '#78716c',
                    600: '#57534e',
                    700: '#44403c',
                    800: '#292524',
                    900: '#1c1917',
                    950: '#0c0a09',
                },
                "surface-container": "#191919",
                "on-tertiary-fixed": "#484a4a",
                "error": "#ee7d77",
                "secondary-fixed": "#d5e7d6",
                "on-surface-variant": "#ababab",
                "surface-dim": "#0e0e0e",
                "tertiary": "#f9f9f9",
                "surface-tint": "#c6c6c7",
                "tertiary-fixed-dim": "#e5e5e5",
                "secondary": "#91a293",
                "on-secondary-fixed-variant": "#4f5f52",
                "inverse-on-surface": "#555555",
                "surface": "#0e0e0e",
                "secondary-fixed-dim": "#c7d9c8",
                "on-secondary-container": "#b2c4b3",
                "primary-fixed": "#e2e2e2",
                "outline": "#757575",
                "on-error-container": "#ff9993",
                "background": "#0e0e0e",
                "tertiary-fixed": "#f4f3f3",
                "on-surface": "#e5e5e5",
                "surface-variant": "#262626",
                "secondary-dim": "#91a293",
                "on-background": "#e5e5e5",
                "surface-container-lowest": "#000000",
                "error-dim": "#bb5551",
                "surface-container-low": "#131313",
                "on-secondary-fixed": "#334337",
                "on-primary-container": "#d0d0d0",
                "primary-dim": "#b8b9b9",
                "on-secondary": "#152318",
                "on-primary-fixed-variant": "#5a5c5c",
                "outline-variant": "#484848",
                "inverse-surface": "#f9f9f9",
                "error-container": "#7f2927",
                "surface-container-high": "#1f1f1f",
                "secondary-container": "#303f33",
                "primary-fixed-dim": "#d4d4d4",
                "tertiary-container": "#ebebeb",
                "on-error": "#490106",
                "on-primary-fixed": "#3e4040",
                "on-primary": "#3f4041",
                "on-tertiary-fixed-variant": "#656666",
                "inverse-primary": "#5e5f60",
                "on-tertiary": "#5e5f5f",
                "primary": "#c6c6c7",
                "primary-container": "#454747",
                "surface-bright": "#2c2c2c",
                "surface-container-highest": "#262626",
                "on-tertiary-container": "#555757",
                "tertiary-dim": "#ebebeb"
            },
        },
    },
    plugins: [
        require('@tailwindcss/container-queries')
    ],
};

export default config;
