const FUNCTION_TARGETS = Object.freeze({
  claimNewsletterReward: 'claimNewsletterRewardGen2',
  clearAllAffiliateClicks: 'clearAllAffiliateClicks',
  clearAllSessions: 'clearAllSessions',
  deleteSession: 'deleteSession',
  addAdminUser: 'addAdminUserGen2',
  completeBillingGuideAdmin: 'completeBillingGuideAdminGen2',
  createQuoteRequest: 'createQuoteRequestGen2',
  drawNewsletterReward: 'drawNewsletterRewardGen2',
  ensureAdminAccessRegistry: 'ensureAdminAccessRegistryGen2',
  finalizeQuoteRequest: 'finalizeQuoteRequestGen2',
  generatePasskeyRegistrationOptions: 'generatePasskeyRegistrationOptionsGen2',
  generatePasskeyAuthenticationOptions: 'generatePasskeyAuthenticationOptionsGen2',
  getBillingGuideOperatorStatus: 'getBillingGuideOperatorStatusGen2',
  getBillingGuideStatus: 'getBillingGuideStatusGen2',
  getCatalogPublicationStatus: 'getCatalogPublicationStatusGen2',
  getManualInvoiceWorkspaceAdmin: 'getManualInvoiceWorkspaceAdminGen2',
  getQuoteRequestAdmin: 'getQuoteRequestAdminGen2',
  getUserStats: 'getUserStatsGen2',
  initLiveSession: 'initLiveSessionGen2',
  listMyNewsletterRewards: 'listMyNewsletterRewardsGen2',
  listQuoteRequestsAdmin: 'listQuoteRequestsAdminGen2',
  logUserConnection: 'logUserConnectionGen2',
  prepareManualInvoicePdfAdmin: 'prepareManualInvoicePdfAdminGen2',
  rebuildCatalogSnapshot: 'rebuildCatalogSnapshotGen2',
  removeAdminUser: 'removeAdminUserGen2',
  resetBillingGuideTest: 'resetBillingGuideTestGen2',
  rollbackCatalogSnapshot: 'rollbackCatalogSnapshotGen2',
  saveBillingGuideProgress: 'saveBillingGuideProgressGen2',
  saveManualInvoiceDraftAdmin: 'saveManualInvoiceDraftAdminGen2',
  sendGuestCheckoutOtp: 'sendGuestCheckoutOtpGen2',
  sendCustomerLoginOtp: 'sendCustomerLoginOtpGen2',
  sendManualInvoiceAdmin: 'sendManualInvoiceAdminGen2',
  sendRefundStatusEmailAdmin: 'sendRefundStatusEmailAdminGen2',
  sendTestEmail: 'sendTestEmailGen2',
  verifyGuestCheckoutOtp: 'verifyGuestCheckoutOtpGen2',
  verifyCustomerLoginOtp: 'verifyCustomerLoginOtpGen2',
  verifyPasskeyRegistration: 'verifyPasskeyRegistrationGen2',
  verifyPasskeyAuthentication: 'verifyPasskeyAuthenticationGen2',
  syncSuperAdminClaim: 'syncSuperAdminClaimGen2',
  syncSession: 'syncSessionGen2',
  syncSessionBeacon: 'syncSessionBeaconGen2',
  trackAdminIP: 'trackAdminIPGen2',
  updateQuoteRequestAdmin: 'updateQuoteRequestAdminGen2',
  updateUserSessions: 'updateUserSessionsGen2',
  uploadQuoteRequestPhoto: 'uploadQuoteRequestPhotoGen2',
});

export const getFunctionTarget = (logicalName) => FUNCTION_TARGETS[logicalName] || logicalName;

export const getFunctionsMigrationRegistry = () => ({ ...FUNCTION_TARGETS });
